SageMaker Training controller with e2e test
aws/aws-controllers-k8s pull request #570
Opened 2020-12-10 20:14 UTC by mbaijal

## Description of changes:
Controller for SageMaker TrainingJob resource with integration test. 
 - Updated generator.yaml config file with a specific operation for `StopTrainingJob` and various Status fields
 - code-generated CRD, controller, rbac and manifests to help create installers.
 - e2e tests to create and stop a trainingjob. 
 - Relevant dataset has been added to the bucket.
 - I have also made a minor edit to the `kind-build-test.sh` to print the debug message at the end of the test runs. 

## Pending:
 - Add a trainingJob Test for debugger
 - Add another create test which waits for the job to reach completion
 - Enable SageMaker test scripts to handle multiple test runs of the same kind more seamlessly (Name generation, more modular scripts etc)
 - Find a smaller dataset, or possibly generate one such removing the dependency on the source buckets. 
 - the format of the debug message is not in sync with the rest of the repo. The `[ERROR]` messages in the SageMaker scripts make debugging easier. 
 - Within SageMaker scripts, the docstrings do not follow the same template. 

## Testing
Using personal account, followed instructions on the ACK testing page. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-12-14 20:53 UTC, jaypipes commented on scripts/lib/aws/sagemaker.sh
> +  assert_equal "0" "$?" "Expected success from aws iam create-role --role-name $__role_name, got $?" || exit 1
I mean, it's up to you, but any reason to change these assertion failure messages? Oftentimes I like to keep style-only changes like this in a separate PR that can reviewed apart from functional changes.

2020-12-14 20:53 UTC, jaypipes commented on scripts/lib/aws/sagemaker.sh
> +is_aws_sagemaker_trainingjob_exists() {
I think "aws" is redundant :) Also, to match functions in other `scripts/lib/aws` modules, might be good to call this `sagemaker_trainingjob_exists()`. For example, see the [`sns_topic_exists()` function](https://github.com/aws/aws-controllers-k8s/blob/cc3c433f3407df06554cd7d937f7e0286b33bc59/scripts/lib/aws/sns.sh#L26).

2020-12-14 20:53 UTC, jaypipes commented on scripts/lib/aws/sagemaker.sh
> +get_aws_sagemaker_trainingjob_status() {
`sagemaker_training_job_get_status()`?

2020-12-14 20:53 UTC, jaypipes commented on scripts/lib/aws/sagemaker.sh
> +      echo "$__training_job_name found!"
recommend not placing `echo` statements in functions that just return a 0 or 1. Instead, place `echo` statements where you *call* these functions, if at all.

2020-12-14 20:53 UTC, jaypipes commented on test/e2e/sagemaker/e2e.sh
> +THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
THIS_DIR is defined below on line 29. Can you remove line 29 please?

2020-12-14 20:53 UTC, jaypipes commented on test/e2e/sagemaker/helper/trainingjob/xgboost-train.sh
> +  TRAINING_IMAGE_USWEST2="$TRAINING_IMAGE_REGISTRY.dkr.ecr.$AWS_REGION.amazonaws.com/xgboost:1"
nothing for this particular PR, but generally I shy away from using script-scoped or global-scoped variables like this inside a function. Better to just set these variables outside of a function in the test that is actually setting this up :)

2020-12-15 21:21 UTC, surajkota requested changes

2020-12-15 21:21 UTC, surajkota commented on test/e2e/sagemaker/helper/trainingjob/xgboost-train.sh
> +    if k8s_resource_exists "$TRAINING_JOB_NAME"; then
+1

2020-12-15 21:21 UTC, surajkota commented on test/e2e/sagemaker/helper/trainingjob/xgboost-train.sh
> +  # Verify model exists on SageMaker and matches ARN populated in Status
correct the comment

2020-12-15 21:21 UTC, surajkota commented on test/e2e/sagemaker/helper/trainingjob/xgboost-train.sh
> +    assert_pod_not_restarted $ack_ctrl_pod_id
this should be a common postcheck for all tests ?

2020-12-15 21:21 UTC, surajkota commented on services/sagemaker/cmd/controller/main.go
> +	_ "github.com/aws/aws-controllers-k8s/services/sagemaker/pkg/resource/training_job"
@jaypipes why do we have these imports

2020-12-16 00:10 UTC, jaypipes commented on test/e2e/sagemaker/e2e.sh
> +THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
Don't use `source` then. Instead use `.`

2020-12-17 18:35 UTC, mbaijal commented on services/sagemaker/generator.yaml
> +      source_name: DebugRuleEvaluationStatuses
You I had assumed the same, but not the case - the trainingJobStatus gets updated to the correct completed status without the requeue change.

2020-12-17 18:36 UTC, mbaijal commented on services/sagemaker/generator.yaml
> +      source_name: DebugRuleEvaluationStatuses
++ about the debug status, need to look into that.

2021-01-07 00:27 UTC, mbaijal commented
Closing this Pull Request since the SageMaker Tests are now being written using Python.

2021-01-07 00:27 UTC, closed without merging